import * as React from "react";
import Head from "next/head";
import PlanTable from "../component/PlanTable";

const Home = () => {
  return (
    <div>
      <Head>
        <title>通勤速查</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="min-h-screen">
        <PlanTable />
      </div>
    </div>
  );
};

export default Home;
